Vagrant.configure("2") do |c|
  #
  # Configure CloudStack
  #
  c.vm.provider :cloudstack do |p|
    p.api_key               = ENV["CLOUDSTACK_API_KEY"]
    p.secret_key            = ENV["CLOUDSTACK_SECRET_KEY"]
    p.host                  = ENV["CLOUDSTACK_HOST"]
    p.zone_name             = ENV["ZONE_NAME"]
    p.service_offering_name = ENV["SERVICE_OFFERING_NAME"]
    p.network_name          = ENV["NETWORK_NAME"]
    p.pf_ip_address         = ENV["PUBLIC_SOURCE_NAT_IP"]
    p.network_type          = "Advanced"
    p.pf_open_firewall      = true
    p.pf_trusted_networks   = "xxx.xxx.xxx.xxx/32,yyy.yyy.yyy.yyy/24"
        
    p.expunge_on_destroy    = true

    p.ssh_key               = './vagacs.key'
    p.keypair               = 'vagacs'
    p.ssh_user              = 'bootstrap'
  end

  # Linux machine
  c.vm.define "linacs-1" do |config|
    config.vm.box           = 'Centos-template-name'
  end
end
