Vagrant.configure("2") do |c|
  #
  # Configure CloudStack
  #
  c.vm.provider :cloudstack do |p|
    p.api_key               = ENV["CLOUDSTACK_API_KEY"]     || "__Your_CloudStack_API_KEY_Here_if_not_set_as_environment_variable__"
    p.secret_key            = ENV["CLOUDSTACK_SECRET_KEY"]  || "__Your_CloudStack_SECRET_KEY_Here_if_not_set_as_environment_variable__"
    p.host                  = ENV["CLOUDSTACK_HOST"]        || "__Your_CloudStackHost_Here__"
    p.zone_name             = ENV["ZONE_NAME"]              || "__Your_CloudStack_Zone_Name_Here__"
    p.service_offering_name = ENV["SERVICE_OFFERING_NAME"]  || "__Your_CloudStack_Service_Offering_Here__"
    p.network_name          = ENV["NETWORK_NAME"]           || "__Your_CloudStack_Network_Name_Here__"
    p.pf_ip_address         = ENV["PUBLIC_SOURCE_NAT_IP"]   || "__Your_Public_IP_Of_Above_CloudStack_Network_Name_Here__"
    p.network_type          = "Advanced"
    p.pf_open_firewall      = true
    p.pf_trusted_networks   = "xxx.xxx.xxx.xxx/32,yyy.yyy.yyy.yyy/24"
        
    p.expunge_on_destroy    = true

    p.ssh_key               = './vagacs.key'
    p.keypair               = 'vagacs'
    p.ssh_user              = 'bootstrap'

#    p.firewall_rules = [
#      { :ipaddress => p.pf_ip_address, :protocol => "tcp", :startport => 1111, :endport => 1111 }
#    ]
#    p.port_forwarding_rules = [
#      { :ipaddress => p.pf_ip_address, :protocol => "tcp", :publicport => 1111, :privateport  => 22, :openfirewall => p.pf_open_firewall }
#    ]
  end

  # Linux machines
  (1...3).each do |vmx|
    c.vm.define "linacs-#{vmx}" do |config|
      config.vm.box           = 'Centos-template-name'
    end
  end
end
